version: '3.8'
services:
  web:
    restart: always
    container_name: nonsimpletodo
    build:
      context: .
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
